name: learn-github-actions
on: [push]
jobs:
  Build_PDFs:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install pandoc & fonts
        run: sudo apt-get install -y pandoc texlive-xetex texlive-fonts-extra texlive-fonts-recommended

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python requirements
        run: pip3 install -r requirements.txt

      - run: mkdir -p output

      - name: Run pandoc
        run: pandoc -V papersize:a4 --highlight-style breezeDark --pdf-engine xelatex -o article.pdf article.md

      - name: Mv files to output folder
        run: mv *.pdf output

      - uses: actions/upload-artifact@v3
        with:
          name: pdf_output
          path: |
            output/article.pdf

